// dnsmasq.rs — generate /etc/dnsmasq.d/pxe.conf from the DB config + reload.
// Source of truth = config + machines tables. Shared by the `setup` subcommand and the M8 API.
use rusqlite::Connection;
use std::process::Command;

use crate::db;

/// First 3 octets of a subnet/ip ("10.0.0.0" -> "10.0.0").
fn prefix3(addr: &str) -> String {
    let p: Vec<&str> = addr.split('.').collect();
    if p.len() == 4 {
        format!("{}.{}.{}", p[0], p[1], p[2])
    } else {
        addr.to_string()
    }
}

/// dhcp-host bindings from the machine table (only machines with both ip + hostname).
pub fn bindings(conn: &Connection) -> Vec<String> {
    let mut stmt = conn
        .prepare("SELECT mac,ip,hostname FROM machines WHERE ip IS NOT NULL AND hostname IS NOT NULL")
        .unwrap();
    let rows = stmt
        .query_map([], |r| {
            Ok(format!(
                "dhcp-host={},{},{}",
                r.get::<_, String>(0)?,
                r.get::<_, String>(1)?,
                r.get::<_, String>(2)?
            ))
        })
        .unwrap();
    rows.filter_map(|r| r.ok()).collect()
}

/// Generate pxe.conf content for the current config (proxy | full).
pub fn generate(conn: &Connection, binds: &[String]) -> String {
    let iface = db::get_config(conn, "dhcp_iface", "");
    let ip = db::get_config(conn, "dhcp_server_ip", "");
    let subnet = db::get_config(conn, "dhcp_subnet", "");
    let mode = db::get_config(conn, "dhcp_mode", "proxy");

    let mut s = String::new();
    s.push_str("# Auto-generated by bootrom-mgmt (dnsmasq.rs). DO NOT edit by hand.\n");
    s.push_str(&format!("interface={iface}\nbind-interfaces\nport=0\n\n"));
    s.push_str("enable-tftp\ntftp-root=/srv/tftp\n\n");
    // Detect arch: UEFI x64 (7,9). An already-loaded iPXE sends option 175.
    s.push_str("dhcp-match=set:efi-x64,option:client-arch,7\n");
    s.push_str("dhcp-match=set:efi-x64,option:client-arch,9\n");
    s.push_str("dhcp-match=set:ipxe,175\n\n");

    if mode == "full" {
        let mut start = db::get_config(conn, "dhcp_range_start", "");
        if start.is_empty() {
            start = format!("{}.100", prefix3(&subnet));
        }
        let mut end = db::get_config(conn, "dhcp_range_end", "");
        if end.is_empty() {
            end = format!("{}.200", prefix3(&subnet));
        }
        let netmask = db::get_config(conn, "dhcp_netmask", "255.255.255.0");
        let lease = db::get_config(conn, "dhcp_lease", "12h");
        let gw = db::get_config(conn, "dhcp_gateway", "");
        let dns = db::get_config(conn, "dhcp_dns", "");

        s.push_str("# FULL DHCP mode — dnsmasq hands out IPs + bootfile (UEFI picks it up directly)\n");
        s.push_str("dhcp-authoritative\n");
        s.push_str(&format!("dhcp-range={start},{end},{netmask},{lease}\n"));
        if !gw.is_empty() {
            s.push_str(&format!("dhcp-option=3,{gw}\n"));
        }
        if !dns.is_empty() {
            s.push_str(&format!("dhcp-option=6,{dns}\n"));
        }
        s.push_str(&format!("dhcp-boot=tag:efi-x64,tag:!ipxe,snponly.efi,,{ip}\n"));
        s.push_str(&format!("dhcp-boot=tag:ipxe,http://{ip}/boot.ipxe?mac=${{net0/mac}}\n"));
        if !binds.is_empty() {
            s.push_str("\n# DHCP binding (M8)\n");
            for b in binds {
                s.push_str(b);
                s.push('\n');
            }
        }
    } else {
        s.push_str("# proxyDHCP mode — another router hands out IPs, only boot info is answered\n");
        s.push_str(&format!("dhcp-range={subnet},proxy\n"));
        s.push_str("dhcp-boot=tag:efi-x64,tag:!ipxe,snponly.efi\n");
        s.push_str(&format!("dhcp-boot=tag:ipxe,http://{ip}/boot.ipxe?mac=${{net0/mac}}\n"));
        s.push_str("pxe-service=tag:efi-x64,x86-64_EFI,\"iPXE UEFI Boot\",snponly.efi\n");
    }

    s.push_str("\nlog-dhcp\n");
    s
}

/// Write pxe.conf + restart dnsmasq. Returns (ok_reload).
pub fn apply(conn: &Connection) -> std::io::Result<bool> {
    let binds = bindings(conn);
    let conf = generate(conn, &binds);
    std::fs::write("/etc/dnsmasq.d/pxe.conf", conf)?;
    let ok = Command::new("systemctl")
        .args(["restart", "dnsmasq"])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    Ok(ok)
}
